### ISSUE TITLE
No new papers error

### ISSUE THREAD

**Issue by sleepymalc** [tatsu-lab/gpt_paper_assistant#4]
Hi, it seems like starting from today, the current implementation doesn't work anymore due to the following unexpected error:

```json
No new papers since Fri, 17 Nov 2023 23:34:59 GMT for cs.CL
Traceback (most recent call last):
  File "/home/runner/work/GPT-Paper-Assistant/GPT-Paper-Assistant/main.py", line 193, in <module>
    papers = list(get_papers_from_arxiv(config))
  File "/home/runner/work/GPT-Paper-Assistant/GPT-Paper-Assistant/main.py", line 154, in get_papers_from_arxiv
    papers = get_papers_from_arxiv_rss_api(area.strip(), config)
  File "/home/runner/work/GPT-Paper-Assistant/GPT-Paper-Assistant/arxiv_scraper.py", line [12](https://github.com/sleepymalc/GPT-Paper-Assistant/actions/runs/6916931816/job/18817517300#step:5:13)6, in get_papers_from_arxiv_rss_api
    paper_list, timestamp, last_id = get_papers_from_arxiv_rss(area, config)
ValueError: not enough values to unpack (expected 3, got 0)
Error: Process completed with exit code 1.
```

Needless to say, after checking http://export.arxiv.org/rss/cs.CL, there does have some new papers today for cs.GL. Moreover, seems like your current deployment also encounters such problem.

**Comment by thashim** [comment]
Bug should be fixed as of https://github.com/tatsu-lab/gpt_paper_assistant/commit/13d54f13fc10c0c61897215f29560fefe44d7a0e . 

Issue can't be replicated right now since that code path should only trigger on saturday/sunday when there are no new papers announced. While the RSS feed shows papers, those are papers that were already grabbed on Friday. In either case, no papers will be missed due to this bug.

**Comment by sleepymalc** [comment]
I guess there's still a bug somewhere. I encounter the same output as [this run](https://github.com/tatsu-lab/gpt_paper_assistant/actions/runs/6981104067), and also today's run (no paper today).
